import { Poppins } from 'next/font/google'
import localFont from "next/font/local";
import './globals.css'

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.variable} ${lpmq.variable}`}>
      <body>{children}</body>
    </html>
  )
}

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const poppins = Poppins({ 
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500', '600', '700', '800'],
  variable: '--font-poppins',
 })

 const lpmq = localFont({
  src:'./lpmq.woff2',
  style:'normal',
  weight:'400',
  variable:'--font-lpmq',
  display: 'swap',
  fallback:['Tahoma','sans-serif']
 })