import { lpmq, poppins } from '~/lib/fonts';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="id" className={`${poppins.variable} ${lpmq.variable}`}>
      <body>{children}</body>
    </html>
  );
}
